[["/usr/lib/python3/dist-packages/pam/__init__.py",[false,[["PAM_ACCT_EXPIRED",true,2,["PAM_ACCT_EXPIRED","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_AUTHINFO_UNAVAIL",true,2,["PAM_AUTHINFO_UNAVAIL","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_AUTHTOK_DISABLE_AGING",true,2,["PAM_AUTHTOK_DISABLE_AGING","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_AUTHTOK_ERR",true,2,["PAM_AUTHTOK_ERR","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_ABORT",true,2,["PAM_ABORT","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_AUTHTOK_EXPIRED",true,2,["PAM_AUTHTOK_EXPIRED","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_AUTHTOK_LOCK_BUSY",true,2,["PAM_AUTHTOK_LOCK_BUSY","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_AUTHTOK_RECOVER_ERR",true,2,["PAM_AUTHTOK_RECOVER_ERR","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_AUTH_ERR",true,2,["PAM_AUTH_ERR","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_BAD_ITEM",true,2,["PAM_BAD_ITEM","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_BUF_ERR",true,2,["PAM_BUF_ERR","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_CHANGE_EXPIRED_AUTHTOK",true,2,["PAM_CHANGE_EXPIRED_AUTHTOK","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_CONV",true,2,["PAM_CONV","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_CONV_ERR",true,2,["PAM_CONV_ERR","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_CRED_ERR",true,2,["PAM_CRED_ERR","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_CRED_EXPIRED",true,2,["PAM_CRED_EXPIRED","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_CRED_INSUFFICIENT",true,2,["PAM_CRED_INSUFFICIENT","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_CRED_UNAVAIL",true,2,["PAM_CRED_UNAVAIL","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_DATA_SILENT",true,2,["PAM_DATA_SILENT","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_DELETE_CRED",true,2,["PAM_DELETE_CRED","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_DISALLOW_NULL_AUTHTOK",true,2,["PAM_DISALLOW_NULL_AUTHTOK","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_ERROR_MSG",true,2,["PAM_ERROR_MSG","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_ESTABLISH_CRED",true,2,["PAM_ESTABLISH_CRED","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_IGNORE",true,2,["PAM_IGNORE","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_MAXTRIES",true,2,["PAM_MAXTRIES","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_MODULE_UNKNOWN",true,2,["PAM_MODULE_UNKNOWN","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_NEW_AUTHTOK_REQD",true,2,["PAM_NEW_AUTHTOK_REQD","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_NO_MODULE_DATA",true,2,["PAM_NO_MODULE_DATA","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_OPEN_ERR",true,2,["PAM_OPEN_ERR","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_PERM_DENIED",true,2,["PAM_PERM_DENIED","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_PROMPT_ECHO_OFF",true,2,["PAM_PROMPT_ECHO_OFF","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_PROMPT_ECHO_ON",true,2,["PAM_PROMPT_ECHO_ON","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_REFRESH_CRED",true,2,["PAM_REFRESH_CRED","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_REINITIALIZE_CRED",true,2,["PAM_REINITIALIZE_CRED","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_RHOST",true,2,["PAM_RHOST","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_RUSER",true,2,["PAM_RUSER","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_SERVICE",true,2,["PAM_SERVICE","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_SERVICE_ERR",true,2,["PAM_SERVICE_ERR","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_SESSION_ERR",true,2,["PAM_SESSION_ERR","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_SILENT",true,2,["PAM_SILENT","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_SUCCESS",true,2,["PAM_SUCCESS","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_SYMBOL_ERR",true,2,["PAM_SYMBOL_ERR","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_SYSTEM_ERR",true,2,["PAM_SYSTEM_ERR","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_TEXT_INFO",true,2,["PAM_TEXT_INFO","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_TRY_AGAIN",true,2,["PAM_TRY_AGAIN","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_TTY",true,2,["PAM_TTY","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_USER",true,2,["PAM_USER","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_USER_PROMPT",true,2,["PAM_USER_PROMPT","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_USER_UNKNOWN",true,2,["PAM_USER_UNKNOWN","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["PAM_XDISPLAY",true,2,["PAM_XDISPLAY","/usr/lib/python3/dist-packages/pam/__internals.py",14]],["authenticate",true,12,null],["pam",true,13,null]]]]]